language: java

before install: openssl aes-256-cbc -K $encrypted_ec63a96903b3_key -iv $encrypted_ec63a96903b3_iv -in /home/travis/build/israeli-whist-dev/israeli-whist-server/whist-game-production-847885794860.json.enc -out /home/travis/build/israeli-whist-dev/israeli-whist-server/whist-game-production-847885794860.json -d

install: 
  - ./mvnw install
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl 
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
  script:
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    # Add gcloud to $PATH
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud version

services:
  - docker

dist: trusty
 
      
before deploy:
- gcloud config set project whist-game-production
- gcloud auth activate-service-account --key-file ${HOME}/build/israeli-whist-dev/israeli-whist-server/whist-game-production-847885794860.json
- gcloud docker -- push gcr.io/whist-game-production/docker-maven-test:0.0.1-SNAPSHOT

deploy: 
  skip_cleanup: true
  provider: script
  script:
  - gcloud container clusters get-credentials whist-game-cluster-production --zone us-central1-c 
  - kubectl set image deployment/whist-backend whist-backend=gcr.io/whist-game-production/docker-maven-test:0.0.1-SNAPSHOT:$TRAVIS_COMMIT
    