language: java

before install: openssl aes-256-cbc -K $encrypted_8bbfaf2ee9e4_key -iv $encrypted_8bbfaf2ee9e4_iv -in whist-game-production-c2e47c08e54c.json.enc -out whist-game-production-c2e47c08e54c.json -d

install: ./mvnw install 

after install:
  - ls -l /home/travis
  - ls -l

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u whistteam -p MayTheForceBeWithYou1!
      - docker push whistteam/docker-maven-test

script: "echo 'Building Docker image with tags'"

deploy: 
  - provider: script
    script: 
      - gcloud auth activate-service-account --key-file ${HOME}/whist-game-production-c2e47c08e54c.json ls -l 
      - kubectl set image deployment/${KUBE_DEPLOYMENT_NAME} ${KUBE_DEPLOYMENT_CONTAINER_NAME}=hub.docker.com/r/whistteam/${whist-game-production}/${docker-maven-test}:$TRAVIS_COMMIT
      