language: java

install: ./mvnw install 

services:
  - docker

  dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u "$whistteam" --password-stdin MayTheForceBeWithYou1!
      - docker tag travis-ci-build-stages-demo $whistteam/travis-ci-build-stages-demo
      - docker push $whistteam/travis-ci-build-stages-demo
    - stage: test
      script: docker run --rm $whistteam/travis-ci-build-stages-demo cat hello.txt
    - script: docker run --rm $whistteam/travis-ci-build-stages-demo cat hello.txt

script: "echo 'Building Docker image with tags'"

after_success:
  - export DEPLOY_TIMESTAMP=`date +'%Y%m%d-%H%M%S'`
  - docker build -t demo:$DEPLOY_TIMESTAMP-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH -t demo:latest .

deploy:
  provider: gcs
  access_key_id: "GCS Interoperable Access Key ID"
  secret_access_key: "GCS Interoperable Access Secret"
  bucket: "GCS Bucket"
  skip_cleanup: true
  on:
    branch: master
  