language: java

install: ./mvnw install 

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u whistteam -p MayTheForceBeWithYou1!
      - docker push whistteam/docker-maven-test

script: "echo 'Building Docker image with tags'"

deploy: 
  - provider: script
    script: 
      - gcloud auth activate-service-account --key-file ${HOME}/whist-game-production-c2e47c08e54c.json
      - kubectl create deployment docker-maven-test-deployment --image=gcr.io/${whist-game-production}/docker-maven-test-deployment:v1
    
      skip_cleanup: true
    on:
      branch: master
  