language: java

before install: openssl aes-256-cbc -K $encrypted_8bbfaf2ee9e4_key -iv $encrypted_8bbfaf2ee9e4_iv -in /home/travis/build/israeli-whist-dev/israeli-whist-server/whist-game-production-c2e47c08e54c.json.enc -out /home/travis/build/israeli-whist-dev/israeli-whist-server/whist-game-production-c2e47c08e54c.json -d

install: 
  - ./mvnw install
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl 
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
  script:
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    # Add gcloud to $PATH
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud version

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u whistteam -p MayTheForceBeWithYou1!
      - docker push whistteam/docker-maven-test


deploy: 
  skip_cleanup: true
  provider: script
  script: ./Whist_Production_Deploy.sh
    