language: java

# setting environment variables
env:
  global:
    - PROJECT_NAME_PRD = whist-game-production
    - DOCKER_IMAGE_NAME = docker-maven-test
    - KUBE_DEPLOYMENT_NAME = whist-game-cluster-production	
    - KUBE_DEPLOYMENT_CONTAINER_NAME = docker-maven-test

install: ./mvnw install 

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u whistteam -p MayTheForceBeWithYou1!
      - docker push whistteam/docker-maven-test

script: "echo 'Building Docker image with tags'"

deploy: 
  - provider: script
    script: 
      - gcloud auth activate-service-account --key-file ${HOME}/whist-game-production-c2e47c08e54c.json
      - kubectl set image deployment/${KUBE_DEPLOYMENT_NAME} ${KUBE_DEPLOYMENT_CONTAINER_NAME}=gcr.io/${PROJECT_NAME_PRD}/${DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT
    
      skip_cleanup: true
    on:
      branch: master
  