language: java

before install: openssl aes-256-cbc -K $encrypted_8bbfaf2ee9e4_key -iv $encrypted_8bbfaf2ee9e4_iv -in /home/travis/build/israeli-whist-dev/israeli-whist-server/whist-game-production-c2e47c08e54c.json.enc -out /home/travis/build/israeli-whist-dev/israeli-whist-server/whist-game-production-c2e47c08e54c.json -d

install: 
  - ./mvnw install
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl 
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config


services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u whistteam -p MayTheForceBeWithYou1!
      - docker push whistteam/docker-maven-test


deploy: 
  skip_cleanup: true
  - provider: script
    script: gcloud config set account 'Whist Game'
  - provider: script
    script: gcloud container clusters get-credentials whist-game-cluster-production --zone us-central1-c
  - provider: script
    script: gcloud auth activate-service-account --key-file ${HOME}/build/israeli-whist-dev/israeli-whist-server/whist-game-production-c2e47c08e54c.json && kubectl set image deployment/whist-backend whist-backend=hub.docker.com/r/whistteam/whist-game-production/docker-maven-test:$TRAVIS_COMMIT
    
     
      