language: java

install: ./mvnw install 

services:
  - docker

dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u whistteam -p MayTheForceBeWithYou1!
      - docker push whistteam/docker-maven-test

script: "echo 'Building Docker image with tags'"


deploy: 
  provider: script
  script:
    args: ["-c", "docker login --username=[$DOCKERHUB_USER] --password=$DOCKERHUB_PASSWORD"]
  