steps:
    - name: gcr.io/cloud-builders/gcloud
      args:
        - kms
        - decrypt
        - --ciphertext-file=.env.enc
        - --plaintext-file=.env
        - --location=global
        - --keyring=whist-keyring
        - --key=whist-key
    
    - name: maven
      entrypoint: mvn
      args: ['-Dgit-revision=$REVISION_ID', 'install']
        
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/whist-game-production/docker-maven-test:$REVISION_ID"]

    - name: "gcr.io/cloud-builders/kubectl"
      args:
        - "set"
        - "image"
        - "deployment/whist-server"
        - "docker-maven-test-sha256-1=gcr.io/whist-game-production/whist-server:$REVISION_ID"
      env:
        - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
        - "CLOUDSDK_CONTAINER_CLUSTER=whist-game-cluster-production"
