steps:
    - name: gcr.io/cloud-builders/gcloud
      args:
        - kms
        - decrypt
        - --ciphertext-file=.env-dev.enc
        - --plaintext-file=.env
        - --location=global
        - --keyring=trending-bay-dev-keyring
        - --key=trending-bay-dev-key
    - name: gcr.io/cloud-builders/gcloud
      args:
        - kms
        - decrypt
        - --ciphertext-file=.flaskenv-dev.enc
        - --plaintext-file=.flaskenv
        - --location=global
        - --keyring=trending-bay-dev-keyring
        - --key=trending-bay-dev-key
    - name: "gcr.io/cloud-builders/docker"
      args:
        ["build", "-t", "gcr.io/trending-bay-development/trending-bay-server:$REVISION_ID", "."]
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/trending-bay-development/trending-bay-server:$REVISION_ID"]
    - name: "gcr.io/cloud-builders/kubectl"
      args:
        - "set"
        - "image"
        - "deployment/trending-bay-server"
        - "trending-bay-server-sha256-1=gcr.io/trending-bay-development/trending-bay-server:$REVISION_ID"
      env:
        - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
        - "CLOUDSDK_CONTAINER_CLUSTER=trending-bay-dev-cluster"